# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171208_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(to='app01.Role', verbose_name='担任的角色'),
        ),
    ]
