# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='权限名')),
                ('url', models.CharField(max_length=16, verbose_name='含正则的URL')),
                ('code', models.CharField(max_length=10, verbose_name='组中别名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.PermissionGroup', verbose_name='所属权限组')),
            ],
            options={
                'verbose_name_plural': '权限表',
            },
        ),
    ]
