# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20171113_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=64, verbose_name='含正则的URL'),
        ),
    ]
